name: easy_service_manager
description: This Package is used to add post production settings and features like more app settings, in-app-review, app rating system etc.
version: 26.0.0
homepage: https://pub.dartlang.org/packages/easy_service_manager
publish_to: none

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  app_tracking_transparency: ^2.0.6+1
  easy_ads_flutter:
    git:
      url: https://github.com/nooralibutt/easy-ads.git
      ref: all-ads-master
  flutter:
    sdk: flutter
  flutter_local_notifications: ^21.0.0
  http: ^1.6.0
  in_app_review: ^2.0.11
  loading_indicator: ^3.1.1
  package_info_plus: ^9.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  timezone: ^0.11.0
  unity_ads_plugin: ^0.3.29
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
