name: easy_service_manager
description: This Package is used to add post production settings and features like more app settings, in-app-review, app rating system etc.
version: 1.5.0
homepage: https://pub.dartlang.org/packages/easy_service_manager

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.1.0
  share_plus: ^10.1.0
  url_launcher: ^6.3.1
  in_app_review: ^2.0.9
  shared_preferences: ^2.3.2
  easy_ads_flutter: ^2.7.0
  app_tracking_transparency: ^2.0.6
  http: ^1.2.2
  unity_ads_plugin: ^0.3.21
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
